# Generated by Django 6.0 on 2025-12-11 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumaria', '0003_carrosselimagem_remove_perfume_imagem_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['ordem']},
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='descricao',
        ),
        migrations.AddField(
            model_name='categoria',
            name='ordem',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='categoria',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='carrosselimagem',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carrosselimagem',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='carrossel/'),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfumes', to='perfumaria.categoria'),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
