# Generated by Django 6.0 on 2025-12-11 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumaria', '0004_alter_categoria_options_remove_categoria_descricao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Quem Somos', max_length=200)),
                ('descricao', models.TextField()),
                ('link_politicas_devolucao', models.URLField(blank=True, null=True)),
                ('link_politicas_privacidade', models.URLField(blank=True, null=True)),
                ('link_termos_uso', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Informação do Footer',
                'verbose_name_plural': 'Informações do Footer',
            },
        ),
    ]
