# Generated by Django 6.0 on 2025-12-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumaria', '0005_footerinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaginaEstatica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pagina', models.CharField(choices=[('PRIVACIDADE', 'Política de Privacidade'), ('TERMOS', 'Termos de Uso'), ('SOBRE', 'Sobre nós'), ('CONTATO', 'Página de Contato'), ('DEVOLUCAO', 'Política de Devolução')], default='PRIVACIDADE', max_length=20, unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('conteudo', models.TextField()),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Página Estática',
                'verbose_name_plural': 'Páginas Estáticas',
                'ordering': ['tipo_pagina'],
            },
        ),
    ]
