# Generated by Django 6.0 on 2025-12-16 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumaria', '0006_paginaestatica'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='imagem',
            field=models.ImageField(blank=True, help_text='Formatos suportados: JPG, PNG, GIF. Tamanho máximo: 5MB', null=True, upload_to='perfumes/', verbose_name='Foto do Perfume'),
        ),
    ]
