# Generated by Django 6.0 on 2026-01-05 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumaria', '0009_comentarioavaliacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='estoque',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
