# Generated by Django 6.0 on 2026-01-05 02:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumaria', '0010_perfume_estoque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarioavaliacao',
            name='avaliacao',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
