# Generated by Django 6.0 on 2026-01-07 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumaria', '0014_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='perfumaria.pedido'),
        ),
    ]
