# Generated by Django 6.0 on 2026-01-08 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumaria', '0016_remove_cartitem_pedido_itempedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfume',
            name='estoque',
            field=models.SmallIntegerField(default=0),
        ),
    ]
