# Generated by Django 6.0 on 2026-01-08 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumaria', '0017_alter_perfume_estoque'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='bloqueado_ate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='primeiro_login',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='senha_obrigatoria_alterar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfil',
            name='tentativas_erro_senha',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='perfil',
            name='ultima_tentativa_erro',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
